### ISSUE TITLE
Release binaries

### ISSUE THREAD

**Issue by kaushalyap** [AdaShoelace/hadlock#47]
Instead of having to compile code, please consider releasing binaries for Linux and macOS with checksums.

**Comment by AdaShoelace** [comment]
I have been looking into releasing a package in AUR but haven't had the time to actually sit down and do it. I don't actually have a mac to test on and releasing untested binaries is not something I'm interested in. 

If you have the possibility to test on a mac an perhaps tweak the github actions to put the latest build to master as a new release (for now) I'm more than happy to take a pull request!

**Comment by AdaShoelace** [comment]
I just threw together some hacky workflow for releasing binaries for linux. Will need to add macOS once it's tested on macOS.

**Comment by AdaShoelace** [comment]
Releases will be published via github actions. So this issue is to be considered resolved.
