### ISSUE TITLE
Add Cargo.lock

### ISSUE THREAD

**Issue by orhun** [AdaShoelace/hadlock#61]
You should consider adding the Cargo.lock file as stated here in the [.gitignore](https://github.com/AdaShoelace/hadlock/blob/master/.gitignore#L5).

See: https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries

**Comment by AdaShoelace** [comment]
It has now been added.
Thanks for letting me now.
