### ISSUE TITLE
AUR Packages

### ISSUE THREAD

**Issue by orhun** [AdaShoelace/hadlock#62]
Hi,
I'm a Rust developer who [maintains](https://github.com/orhun/PKGBUILDs) [AUR](https://wiki.archlinux.org/index.php/Arch_User_Repository) packages in his spare time. I created the following packages for the installation of `hadlock` on Arch Linux and other distributions that support installing packages from [AUR](https://aur.archlinux.org/):

* [hadlock](https://aur.archlinux.org/packages/hadlock/) (builds from source)
* [hadlock-git](https://aur.archlinux.org/packages/hadlock-git/) (VCS/development package)
* [hadlock-bin](https://aur.archlinux.org/packages/hadlock-bin/) (installs the latest binary)

Installation can be made simply by using an [AUR helper](https://wiki.archlinux.org/index.php/AUR_helpers) such as [yay](https://github.com/Jguer/yay). (e.g: `yay -S hadlock`)

Feel free to update the documentation regarding to the AUR packages and installation. (I would propose a PR if requested)

Take care,
orhun.

**Comment by AdaShoelace** [comment]
Thank you so much!
I've been meaning to do this for ages but haven't found the time.

**Comment by orhun** [comment]
🥂 bc666972052011d50795d6cbb1f83d369d62b5c3
